# Use postgres/example user/password credentials

name: postgres16_pgadmin
services:
  postgres:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password.-0
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - C:/Docker/postgres:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: info@wisegar.org
      PGADMIN_DEFAULT_PASSWORD: Password.-0
    ports:
      - "8088:80"
    volumes:
      - C:/Docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
